FROM node:16.13.2-alpine AS build-stage

WORKDIR /var/react-app

COPY ./package*.json ./

RUN npm install --prefer-offline --no-audit --progress=false

COPY . .

RUN npm run build:prod

FROM nginx:1.15-alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build-stage /var/react-app/build/ ./

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
